export type EmployeeSummary = {
  id: number;
  name: string;
  role: string;
  department: string;
  gradient: string;
  initials: string;
  email: string;
};

export const employees: EmployeeSummary[] = [
  { id: 1, name: "Alice Johnson", role: "Software Engineer", department: "Engineering", gradient: "from-violet-200 to-indigo-300", initials: "AJ", email: "alice@company.com" },
  { id: 2, name: "Bob Smith", role: "Product Manager", department: "Product", gradient: "from-sky-200 to-cyan-300", initials: "BS", email: "bob@company.com" },
  { id: 3, name: "Carol White", role: "UX Designer", department: "Design", gradient: "from-pink-200 to-rose-300", initials: "CW", email: "carol@company.com" },
  { id: 4, name: "David Lee", role: "Data Analyst", department: "Analytics", gradient: "from-emerald-200 to-teal-300", initials: "DL", email: "david@company.com" },
  { id: 5, name: "Eva Martinez", role: "HR Manager", department: "Human Resources", gradient: "from-amber-200 to-orange-300", initials: "EM", email: "eva@company.com" },
  { id: 6, name: "Frank Chen", role: "DevOps Engineer", department: "Engineering", gradient: "from-slate-200 to-gray-300", initials: "FC", email: "frank@company.com" },
  { id: 7, name: "Grace Kim", role: "Marketing Lead", department: "Marketing", gradient: "from-fuchsia-200 to-purple-300", initials: "GK", email: "grace@company.com" },
  { id: 8, name: "Henry Brown", role: "Sales Executive", department: "Sales", gradient: "from-red-200 to-rose-300", initials: "HB", email: "henry@company.com" },
  { id: 9, name: "Iris Patel", role: "Backend Engineer", department: "Engineering", gradient: "from-lime-200 to-green-300", initials: "IP", email: "iris@company.com" },
  { id: 10, name: "Jake Thompson", role: "Security Engineer", department: "Engineering", gradient: "from-blue-200 to-indigo-300", initials: "JT", email: "jake@company.com" },
  { id: 11, name: "Karen Liu", role: "Finance Analyst", department: "Finance", gradient: "from-yellow-200 to-amber-300", initials: "KL", email: "karen@company.com" },
  { id: 12, name: "Leo Nguyen", role: "Mobile Engineer", department: "Engineering", gradient: "from-cyan-200 to-blue-300", initials: "LN", email: "leo@company.com" },
  { id: 13, name: "Maya Patel", role: "Data Scientist", department: "Analytics", gradient: "from-rose-200 to-pink-300", initials: "MP", email: "maya@company.com" },
  { id: 14, name: "Omar Hassan", role: "Customer Success Manager", department: "Sales", gradient: "from-teal-200 to-emerald-300", initials: "OH", email: "omar@company.com" },
  { id: 15, name: "Priya Sharma", role: "Legal Counsel", department: "Legal", gradient: "from-indigo-200 to-violet-300", initials: "PS", email: "priya@company.com" },
  { id: 16, name: "Ryan Okafor", role: "Frontend Engineer", department: "Engineering", gradient: "from-orange-200 to-red-300", initials: "RO", email: "ryan@company.com" },
  { id: 17, name: "Sofia Rossi", role: "Brand Designer", department: "Design", gradient: "from-fuchsia-200 to-pink-300", initials: "SR", email: "sofia@company.com" },
  { id: 18, name: "Tom Nakamura", role: "QA Engineer", department: "Engineering", gradient: "from-sky-200 to-blue-300", initials: "TN", email: "tom@company.com" },
  { id: 19, name: "Amara Diallo", role: "Operations Manager", department: "Operations", gradient: "from-lime-200 to-green-300", initials: "AD", email: "amara@company.com" },
  { id: 20, name: "Lena Müller", role: "Content Strategist", department: "Marketing", gradient: "from-amber-200 to-yellow-300", initials: "LM", email: "lena@company.com" },
  { id: 21, name: "Nathan Pierce", role: "Cloud Architect", department: "Engineering", gradient: "from-blue-200 to-sky-300", initials: "NP", email: "nathan@company.com" },
  { id: 22, name: "Olivia Chen", role: "People Partner", department: "Human Resources", gradient: "from-rose-200 to-pink-300", initials: "OC", email: "olivia@company.com" },
  { id: 23, name: "Paulo Ferreira", role: "Sales Engineer", department: "Sales", gradient: "from-green-200 to-emerald-300", initials: "PF", email: "paulo@company.com" },
  { id: 24, name: "Quinn Zhao", role: "Machine Learning Engineer", department: "Analytics", gradient: "from-violet-200 to-purple-300", initials: "QZ", email: "quinn@company.com" },
  { id: 25, name: "Rachel Adams", role: "Scrum Master", department: "Product", gradient: "from-cyan-200 to-teal-300", initials: "RA", email: "rachel@company.com" },
  { id: 26, name: "Samuel Osei", role: "Business Analyst", department: "Operations", gradient: "from-amber-200 to-orange-300", initials: "SO", email: "samuel@company.com" },
  { id: 27, name: "Tanya Brooks", role: "Social Media Manager", department: "Marketing", gradient: "from-pink-200 to-fuchsia-300", initials: "TB", email: "tanya@company.com" },
  { id: 28, name: "Umar Farooq", role: "Infrastructure Engineer", department: "Engineering", gradient: "from-gray-200 to-slate-300", initials: "UF", email: "umar@company.com" },
  { id: 29, name: "Vera Santos", role: "Graphic Designer", department: "Design", gradient: "from-red-200 to-rose-300", initials: "VS", email: "vera@company.com" },
  { id: 30, name: "Walter Kim", role: "Account Executive", department: "Sales", gradient: "from-indigo-200 to-blue-300", initials: "WK", email: "walter@company.com" },
  { id: 31, name: "Xena Volkov", role: "Research Scientist", department: "Analytics", gradient: "from-teal-200 to-cyan-300", initials: "XV", email: "xena@company.com" },
  { id: 32, name: "Yara Al-Rashid", role: "Compliance Officer", department: "Legal", gradient: "from-yellow-200 to-lime-300", initials: "YA", email: "yara@company.com" },
  { id: 33, name: "Zack Monroe", role: "IT Support Specialist", department: "Operations", gradient: "from-orange-200 to-amber-300", initials: "ZM", email: "zack@company.com" },
  { id: 34, name: "Aisha Kamara", role: "Recruiter", department: "Human Resources", gradient: "from-emerald-200 to-green-300", initials: "AK", email: "aisha@company.com" },
  { id: 35, name: "Brett Harrison", role: "Product Designer", department: "Design", gradient: "from-sky-200 to-indigo-300", initials: "BH", email: "brett@company.com" },
  { id: 36, name: "Chloe Dupont", role: "Finance Manager", department: "Finance", gradient: "from-purple-200 to-violet-300", initials: "CD", email: "chloe@company.com" },
  { id: 37, name: "Diego Reyes", role: "Growth Marketer", department: "Marketing", gradient: "from-rose-200 to-red-300", initials: "DR", email: "diego@company.com" },
  { id: 38, name: "Elena Sokolova", role: "Platform Engineer", department: "Engineering", gradient: "from-fuchsia-200 to-purple-300", initials: "ES", email: "elena@company.com" },
  { id: 39, name: "Felix Wagner", role: "Solution Architect", department: "Sales", gradient: "from-blue-200 to-cyan-300", initials: "FW", email: "felix@company.com" },
  { id: 40, name: "Gina Tanaka", role: "Office Manager", department: "Operations", gradient: "from-lime-200 to-teal-300", initials: "GT", email: "gina@company.com" },
  { id: 41, name: "Hugo Morales", role: "Senior Product Manager", department: "Product", gradient: "from-amber-200 to-red-300", initials: "HM", email: "hugo@company.com" },
  { id: 42, name: "Ingrid Larsen", role: "Data Engineer", department: "Analytics", gradient: "from-cyan-200 to-blue-300", initials: "IL", email: "ingrid@company.com" },
  { id: 43, name: "Jordan Kim", role: "Frontend Engineer", department: "Engineering", gradient: "from-violet-200 to-purple-300", initials: "JK", email: "jordan@company.com" },
  { id: 44, name: "Kenji Watanabe", role: "Cloud Engineer", department: "Engineering", gradient: "from-teal-200 to-emerald-300", initials: "KW", email: "kenji@company.com" },
  { id: 45, name: "Lucia Fernandez", role: "Brand Designer", department: "Design", gradient: "from-fuchsia-200 to-pink-300", initials: "LF", email: "lucia@company.com" },
  { id: 46, name: "Marcus Hill", role: "Enterprise AE", department: "Sales", gradient: "from-slate-200 to-blue-300", initials: "MH", email: "marcus@company.com" },
  { id: 47, name: "Nina Kapoor", role: "Analytics Engineer", department: "Analytics", gradient: "from-orange-200 to-red-300", initials: "NK", email: "nina@company.com" },
  { id: 48, name: "Oscar Grant", role: "Operations Analyst", department: "Operations", gradient: "from-cyan-200 to-sky-300", initials: "OG", email: "oscar@company.com" },
  { id: 49, name: "Paula Reed", role: "Senior Product Manager", department: "Product", gradient: "from-violet-200 to-fuchsia-300", initials: "PR", email: "paula@company.com" },
  { id: 50, name: "Quentin Bell", role: "QA Lead", department: "Engineering", gradient: "from-sky-200 to-indigo-300", initials: "QB", email: "quentin@company.com" },
  { id: 51, name: "Rosa Sanchez", role: "Paralegal", department: "Legal", gradient: "from-rose-200 to-red-300", initials: "RS", email: "rosa@company.com" },
  { id: 52, name: "Sebastian Clark", role: "Full Stack Engineer", department: "Engineering", gradient: "from-indigo-200 to-cyan-300", initials: "SC", email: "sebastian@company.com" },
  { id: 53, name: "Tara Singh", role: "Head of People", department: "Human Resources", gradient: "from-amber-200 to-rose-300", initials: "TS", email: "tara@company.com" },
  { id: 54, name: "Uma Patel", role: "Financial Controller", department: "Finance", gradient: "from-teal-200 to-blue-300", initials: "UP", email: "uma@company.com" },
  { id: 55, name: "Victor Cruz", role: "Customer Success Lead", department: "Sales", gradient: "from-green-200 to-lime-300", initials: "VC", email: "victor@company.com" },
  { id: 56, name: "Wendy Zhang", role: "Research Scientist", department: "Analytics", gradient: "from-fuchsia-200 to-indigo-300", initials: "WZ", email: "wendy@company.com" },
  { id: 57, name: "Xavier Dupont", role: "Infrastructure Engineer", department: "Engineering", gradient: "from-gray-200 to-slate-300", initials: "XD", email: "xavier@company.com" },
  { id: 58, name: "Yasmin Ali", role: "Campaigns Manager", department: "Marketing", gradient: "from-pink-200 to-orange-300", initials: "YA", email: "yasmin@company.com" },
  { id: 59, name: "Zara Khan", role: "Interaction Designer", department: "Design", gradient: "from-cyan-200 to-violet-300", initials: "ZK", email: "zara@company.com" },
  { id: 60, name: "Alex Morgan", role: "Growth PM", department: "Product", gradient: "from-lime-200 to-teal-300", initials: "AM", email: "alex@company.com" },
  { id: 61, name: "Brooke Evans", role: "Content Writer", department: "Marketing", gradient: "from-rose-200 to-pink-300", initials: "BE", email: "brooke@company.com" },
  { id: 62, name: "Carlos Reyes", role: "Mobile Engineer", department: "Engineering", gradient: "from-orange-200 to-amber-300", initials: "CR", email: "carlosr@company.com" },
  { id: 63, name: "Diana Walsh", role: "Finance Manager", department: "Finance", gradient: "from-indigo-200 to-blue-300", initials: "DW", email: "diana@company.com" },
  { id: 64, name: "Ethan Brooks", role: "Product Analyst", department: "Product", gradient: "from-teal-200 to-cyan-300", initials: "EB", email: "ethan@company.com" },
  { id: 65, name: "Fatima Al-Rashid", role: "UX Researcher", department: "Design", gradient: "from-emerald-200 to-green-300", initials: "FA", email: "fatima@company.com" },
  { id: 66, name: "George Patel", role: "Platform Engineer", department: "Engineering", gradient: "from-green-200 to-teal-300", initials: "GP", email: "george@company.com" },
  { id: 67, name: "Hannah Lee", role: "Social Media Manager", department: "Marketing", gradient: "from-rose-200 to-fuchsia-300", initials: "HL", email: "hannah@company.com" },
  { id: 68, name: "Ian Foster", role: "Security Analyst", department: "Engineering", gradient: "from-zinc-200 to-slate-300", initials: "IF", email: "ian@company.com" },
  { id: 69, name: "Julia Kim", role: "People Partner", department: "Human Resources", gradient: "from-pink-200 to-rose-300", initials: "JK", email: "julia@company.com" },
  { id: 70, name: "Kevin Zhao", role: "API Engineer", department: "Engineering", gradient: "from-blue-200 to-violet-300", initials: "KZ", email: "kevin@company.com" },
  { id: 71, name: "Lily Turner", role: "Visual Designer", department: "Design", gradient: "from-purple-200 to-pink-300", initials: "LT", email: "lily@company.com" },
  { id: 72, name: "Marco Bianchi", role: "Site Reliability Engineer", department: "Engineering", gradient: "from-emerald-200 to-teal-300", initials: "MB", email: "marco@company.com" },
  { id: 73, name: "Nadia Osei", role: "Talent Acquisition Partner", department: "Human Resources", gradient: "from-fuchsia-200 to-purple-300", initials: "NO", email: "nadia@company.com" },
  { id: 74, name: "Omar Hassan", role: "Customer Success Manager", department: "Sales", gradient: "from-teal-200 to-emerald-300", initials: "OH", email: "omar2@company.com" },
  { id: 75, name: "Petra Novak", role: "Legal Counsel", department: "Legal", gradient: "from-indigo-200 to-violet-300", initials: "PN", email: "petra@company.com" },
  { id: 76, name: "Ravi Krishnamurthy", role: "Backend Engineer", department: "Engineering", gradient: "from-green-200 to-emerald-300", initials: "RK", email: "ravi@company.com" },
  { id: 77, name: "Sophie Müller", role: "Finance Analyst", department: "Finance", gradient: "from-yellow-200 to-amber-300", initials: "SM", email: "sophie@company.com" },
  { id: 78, name: "Tariq Mansouri", role: "DevOps Engineer", department: "Engineering", gradient: "from-sky-200 to-blue-300", initials: "TM", email: "tariq@company.com" },
  { id: 79, name: "Ursula Bergmann", role: "HR Business Partner", department: "Human Resources", gradient: "from-rose-200 to-orange-300", initials: "UB", email: "ursula@company.com" },
  { id: 80, name: "Victor Cruz", role: "Customer Success Lead", department: "Sales", gradient: "from-lime-200 to-green-300", initials: "VC", email: "victor2@company.com" },
  { id: 81, name: "Mei Lin", role: "Support Engineer", department: "Customer Support", gradient: "from-sky-200 to-teal-300", initials: "ML", email: "mei@company.com" },
  { id: 82, name: "Tobias Grant", role: "Support Lead", department: "Customer Support", gradient: "from-cyan-200 to-emerald-300", initials: "TG", email: "tobias@company.com" },
  { id: 83, name: "Amelia Ford", role: "Technical Support Specialist", department: "Customer Support", gradient: "from-teal-200 to-sky-300", initials: "AF", email: "amelia@company.com" },
  { id: 84, name: "Rohan Mehta", role: "VP Business Development", department: "Business Development", gradient: "from-amber-200 to-yellow-300", initials: "RM", email: "rohan@company.com" },
  { id: 85, name: "Claire Dupuis", role: "Partnerships Manager", department: "Business Development", gradient: "from-yellow-200 to-orange-300", initials: "CD", email: "claire@company.com" },
  { id: 86, name: "James Okoro", role: "Strategic Alliances Lead", department: "Business Development", gradient: "from-orange-200 to-yellow-300", initials: "JO", email: "james@company.com" },
  { id: 87, name: "Sandra Lee", role: "CEO", department: "Executive", gradient: "from-violet-300 to-purple-400", initials: "SL", email: "sandra@company.com" },
  { id: 88, name: "Marcus Webb", role: "CTO", department: "Executive", gradient: "from-indigo-300 to-blue-400", initials: "MW", email: "marcus.w@company.com" },
  { id: 89, name: "Fiona Cheng", role: "CFO", department: "Executive", gradient: "from-emerald-300 to-teal-400", initials: "FC", email: "fiona@company.com" },
  { id: 90, name: "Meghana Deep", role: "Full Stack Engineer", department: "Engineering", gradient: "from-purple-200 to-fuchsia-300", initials: "MD", email: "meghanadeep3@gmail.com" },
];
